#!/bin/sh
#/etc/init.d/BeispielVM
#

#Edit these variables!
VMUSER=rephlex
VMNAME="fubar.de"

case "$1" in
start)
echo "compiling modules"
dpkg-reconfigure virtualbox-dkms && modprobe vboxdrv && modprobe vboxnetflt
echo "Starting VirtualBox VM..."
sudo -H -b -u $VMUSER /usr/bin/VBoxManage startvm "$VMNAME" --type headless
;;
stop)
echo "Stopping Virtualbox VM..."
sudo -H -u $VMUSER /usr/bin/VBoxManage controlvm "$VMNAME" acpipowerbutton
sleep 40
;;
*)
echo "Usage: /etc/init.d/BeispielVM {start|stop}"
exit 1
;;
esac

exit 0
